os: linux

services:
  - docker
  
language: go

go:
  - 1.13.x

script:   
  # Test the code
  - go test -v ./...
  # Build the code 
  - env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o demo
  # docker login
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t kuwiano/demo:latest ./

  # tag
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag kuwiano/demo:latest kuwiano/demo:$GIT_SHA

  # push
  - docker push kuwiano/demo:latest
  - docker push kuwiano/demo:$GIT_SHA
